syntax = "proto3";
package auth;

service Auth {
  rpc Register(RegisterRequest) returns (RegisterResponse);
  rpc Login(LoginRequest) returns (LoginResponse);
  rpc Logout(LogoutRequest) returns (LogoutResponse);
}

message RegisterRequest {
  string username = 1;
  string password = 2;
}
message LoginRequest {
  string username = 1;
  string password = 2;
}
message LogoutRequest { string session_token = 1; }

message RegisterResponse { StatusCode status_code = 1; }
message LoginResponse {
  StatusCode status_code = 1;
  string user_id = 2;
  string session_token = 3;
}
message LogoutResponse { StatusCode status_code = 1; }

enum StatusCode {
  FAILURE = 0;
  SUCCESS = 2;
}
